<a href="https://colab.research.google.com/github/ritikgoyal1701/Drowsiness-Detector/blob/main/Logistic_Regression_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Logistic Regression is used for the training of our drowsiness model

Importing important libraries

In [ ]:
import pandas
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Downloading the dataset which we have previously prepared
1. Drowsy
2. Alert

In [ ]:
!wget "https://drive.google.com/uc?id=1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I"

--2021-08-03 08:53:35--  https://drive.google.com/uc?id=1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I
Resolving drive.google.com (drive.google.com)... 74.125.195.113, 74.125.195.138, 74.125.195.101, ...
Connecting to drive.google.com (drive.google.com)|74.125.195.113|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0c-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/h2v46abrtdf44porjt5bijeob4vqhubm/1627980750000/12611103512387577130/*/1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I [following]
--2021-08-03 08:53:37--  https://doc-0c-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/h2v46abrtdf44porjt5bijeob4vqhubm/1627980750000/12611103512387577130/*/1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I
Resolving doc-0c-7k-docs.googleusercontent.com (doc-0c-7k-docs.googleusercontent.com)... 74.125.195.132, 2607:f8b0:400e:c09::84
Connecting to doc-0c-7k-docs.googleusercontent.com (doc-0c-7k-docs.googleusercontent.com)|74.125

In [ ]:
pq=pandas.read_csv("/content/uc?id=1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I")
pq.drop("Unnamed: 0",axis=1,inplace=True)
pq

EAR       MAR       PUC       MOE
0     -1.695219 -0.478695 -2.542126  0.012934
1     -1.117250 -0.088761 -0.374188  0.256548
2     -1.653670 -0.325083 -0.627831  0.174467
3     -1.653670 -0.325083 -0.514742  0.174467
4     -1.653670 -0.405585 -0.514742  0.082690
...         ...       ...       ...       ...
60001 -0.100015  6.067398 -1.258254  5.545738
60002  0.096715  5.119457 -1.274578  4.430580
60003 -0.086904  3.716327 -1.092155  3.403024
60004 -3.176089  2.786678 -2.426750  7.298001
60005 -3.176089  3.785340 -2.617446  8.487523

[60006 rows x 4 columns]

In [ ]:
!wget "https://drive.google.com/uc?id=1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY"

--2021-08-03 08:54:14--  https://drive.google.com/uc?id=1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY
Resolving drive.google.com (drive.google.com)... 74.125.135.139, 74.125.135.100, 74.125.135.102, ...
Connecting to drive.google.com (drive.google.com)|74.125.135.139|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-14-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fc0m8nm7nik5r97uab31sc25jgvmqt60/1627980825000/12611103512387577130/*/1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY [following]
--2021-08-03 08:54:15--  https://doc-14-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fc0m8nm7nik5r97uab31sc25jgvmqt60/1627980825000/12611103512387577130/*/1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY
Resolving doc-14-7k-docs.googleusercontent.com (doc-14-7k-docs.googleusercontent.com)... 74.125.195.132, 2607:f8b0:400e:c09::84
Connecting to doc-14-7k-docs.googleusercontent.com (doc-14-7k-docs.googleusercontent.com)|74.125

In [ ]:
alert=pandas.read_csv("/content/uc?id=1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY")
alert.drop("Unnamed: 0",axis=1, inplace=True)
alert

Converting the csv data to numpy array so as to apply our learning models.

In [ ]:
alert_x=alert.to_numpy()
drowsy_x=pq.to_numpy()
x=np.concatenate((alert_x,drowsy_x))
x

array([[-0.87352174, -1.38037163, -0.06712643, -0.47435762],
       [-0.87352174, -1.38037163, -0.06712643, -0.47435762],
       [-0.87352174, -1.40222759, -0.06712643, -0.49539992],
       ...,
       [-0.08690365,  3.71632729, -1.09215525,  3.40302391],
       [-3.17608894,  2.78667839, -2.42675046,  7.29800137],
       [-3.17608894,  3.78533965, -2.61744601,  8.48752285]])

Now, preparing the value corresponding to each situation.

"0" for Alertness.

"1" for Drowsiness

In [ ]:
alert_y=np.zeros((60006))
drowsy_y=np.ones(60006)
y=np.concatenate((alert_y,drowsy_y))
y

array([0., 0., 0., ..., 1., 1., 1.])

Seggregating our test and training data

In [ ]:
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [ ]:
model1 = LogisticRegression(solver='liblinear', C=0.05, multi_class='ovr',
                           random_state=0)
model1.fit(x_train, y_train)

LogisticRegression(C=0.05, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [ ]:
x_test = scaler.transform(x_test)

In [ ]:
y_pred = model1.predict(x_test)
y_pred

array([1., 0., 1., ..., 0., 1., 0.])

In [ ]:
model1.score(x_train, y_train)

0.5596558655959337

In [ ]:
model1.score(x_test, y_test)

0.5620964046160897

In [ ]:
confusion_matrix(y_test, y_pred)

array([[7474, 4498],
       [6013, 6018]])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.55      0.62      0.59     11972
         1.0       0.57      0.50      0.53     12031

    accuracy                           0.56     24003
   macro avg       0.56      0.56      0.56     24003
weighted avg       0.56      0.56      0.56     24003



This model gives us 56% accuracy.

Saving our trained model for further use.

In [ ]:
import pickle
pickle.dump(model1,open("logistic_model_drowsiness",'wb'))

In [ ]:
p=pickle.load(open("logistic_model_drowsiness",'rb'))

In [ ]:
p.score(x_test,y_test)

0.5620964046160897

In [ ]:
!pip install -U kora
from kora.drive import upload_public
url=upload_public("/content/logistic_model_drowsiness")
url

     |████████████████████████████████| 57 kB 3.1 MB/s 
     |████████████████████████████████| 54 kB 2.7 MB/s 


'https://drive.google.com/uc?id=1nfKjqTNKCRb8JyOJXqEBiVWNDGnNIipg'

Our logistic regression drowsiness model is ready to use and is available at https://drive.google.com/uc?id=1nfKjqTNKCRb8JyOJXqEBiVWNDGnNIipg