<a href="https://colab.research.google.com/github/ritikgoyal1701/Drowsiness-Detector/blob/main/Naive_Bayes_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Naive Bayes is used for the training of our drowsiness model

Importing important libraries

In [11]:
import pandas
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix

Downloading the dataset which we have previously prepared
1. Drowsy
2. Alert

In [2]:
!wget "https://drive.google.com/uc?id=1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I"

--2021-08-03 17:28:11--  https://drive.google.com/uc?id=1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I
Resolving drive.google.com (drive.google.com)... 142.251.2.139, 142.251.2.102, 142.251.2.113, ...
Connecting to drive.google.com (drive.google.com)|142.251.2.139|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0c-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n2s7mltemphcg16nmdq79o4hbl2ri1ej/1628011650000/12611103512387577130/*/1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I [following]
--2021-08-03 17:28:12--  https://doc-0c-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n2s7mltemphcg16nmdq79o4hbl2ri1ej/1628011650000/12611103512387577130/*/1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I
Resolving doc-0c-7k-docs.googleusercontent.com (doc-0c-7k-docs.googleusercontent.com)... 142.251.2.132, 2607:f8b0:4023:c0d::84
Connecting to doc-0c-7k-docs.googleusercontent.com (doc-0c-7k-docs.googleusercontent.com)|142.251.2.1

In [3]:
pq=pandas.read_csv("/content/uc?id=1AE9anQEIJrQnjXU6R4CSew81An-3Qs0I")
pq.drop("Unnamed: 0",axis=1,inplace=True)
pq

EAR       MAR       PUC       MOE
0     -1.695219 -0.478695 -2.542126  0.012934
1     -1.117250 -0.088761 -0.374188  0.256548
2     -1.653670 -0.325083 -0.627831  0.174467
3     -1.653670 -0.325083 -0.514742  0.174467
4     -1.653670 -0.405585 -0.514742  0.082690
...         ...       ...       ...       ...
60001 -0.100015  6.067398 -1.258254  5.545738
60002  0.096715  5.119457 -1.274578  4.430580
60003 -0.086904  3.716327 -1.092155  3.403024
60004 -3.176089  2.786678 -2.426750  7.298001
60005 -3.176089  3.785340 -2.617446  8.487523

[60006 rows x 4 columns]

In [4]:
!wget "https://drive.google.com/uc?id=1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY"

--2021-08-03 17:28:42--  https://drive.google.com/uc?id=1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY
Resolving drive.google.com (drive.google.com)... 142.250.141.113, 142.250.141.101, 142.250.141.139, ...
Connecting to drive.google.com (drive.google.com)|142.250.141.113|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-14-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/3ivc95k6fcjm3k9mf2b1lhb5hcecdr4l/1628011650000/12611103512387577130/*/1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY [following]
--2021-08-03 17:28:43--  https://doc-14-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/3ivc95k6fcjm3k9mf2b1lhb5hcecdr4l/1628011650000/12611103512387577130/*/1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY
Resolving doc-14-7k-docs.googleusercontent.com (doc-14-7k-docs.googleusercontent.com)... 142.251.2.132, 2607:f8b0:4023:c0d::84
Connecting to doc-14-7k-docs.googleusercontent.com (doc-14-7k-docs.googleusercontent.com)|142

In [5]:
alert=pandas.read_csv("/content/uc?id=1698bSBXSWG4ktuSLGdzYAB-arYwhhJjY")
alert.drop("Unnamed: 0",axis=1, inplace=True)
alert

EAR       MAR       PUC       MOE
0     -0.873522 -1.380372 -0.067126 -0.474358
1     -0.873522 -1.380372 -0.067126 -0.474358
2     -0.873522 -1.402228 -0.067126 -0.495400
3     -0.873522  1.326526 -0.067126  2.131768
4      0.627844  1.326526 -0.388594  0.526276
...         ...       ...       ...       ...
60001  1.101467  0.228743  0.921352 -0.073856
60002  0.290266  0.069983 -1.529633 -0.007520
60003  1.901880  0.275737  2.221742 -0.226629
60004  1.101467 -0.078860 -0.313887 -0.354479
60005  1.101467  0.191694  1.083347 -0.107655

[60006 rows x 4 columns]

Converting the csv data to numpy array so as to apply our learning models.

In [6]:
alert_x=alert.to_numpy()
drowsy_x=pq.to_numpy()
x=np.concatenate((alert_x,drowsy_x))
x

array([[-0.87352174, -1.38037163, -0.06712643, -0.47435762],
       [-0.87352174, -1.38037163, -0.06712643, -0.47435762],
       [-0.87352174, -1.40222759, -0.06712643, -0.49539992],
       ...,
       [-0.08690365,  3.71632729, -1.09215525,  3.40302391],
       [-3.17608894,  2.78667839, -2.42675046,  7.29800137],
       [-3.17608894,  3.78533965, -2.61744601,  8.48752285]])

Now, preparing the value corresponding to each situation.

"0" for Alertness.

"1" for Drowsiness


In [7]:
alert_y=np.zeros((60006))
drowsy_y=np.ones(60006)
y=np.concatenate((alert_y,drowsy_y))
y

array([0., 0., 0., ..., 1., 1., 1.])

Training our model

In [9]:
model = GaussianNB()
model.fit(x,y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
model.predict(x)

array([0., 0., 0., ..., 0., 1., 1.])

In [12]:
confusion_matrix(y, model.predict(x))

array([[49839, 10167],
       [37096, 22910]])

In [13]:
print(classification_report(y, model.predict(x)))

              precision    recall  f1-score   support

         0.0       0.57      0.83      0.68     60006
         1.0       0.69      0.38      0.49     60006

    accuracy                           0.61    120012
   macro avg       0.63      0.61      0.59    120012
weighted avg       0.63      0.61      0.59    120012



This model gives us 61% accuracy.

Saving our trained model for further use

In [15]:
import pickle
pickle.dump(model,open("Naive_Bayes_model_drowsiness",'wb'))

In [17]:
p=pickle.load(open("Naive_Bayes_model_drowsiness",'rb'))

In [18]:
p.predict(x)

array([0., 0., 0., ..., 0., 1., 1.])

In [19]:
!pip install -U kora
from kora.drive import upload_public
url=upload_public("/content/Naive_Bayes_model_drowsiness")
url

     |████████████████████████████████| 57 kB 3.6 MB/s 
     |████████████████████████████████| 54 kB 3.3 MB/s 


'https://drive.google.com/uc?id=1DtWhCUMtcocxzP_BEMGw3TrkXQeo2r5O'

Our Naive bayes based drowsiness model is ready to use at

https://drive.google.com/uc?id=1DtWhCUMtcocxzP_BEMGw3TrkXQeo2r5O